services:
  db:
    image: postgres:16
    container_name: pessoas-tarefas-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "#Vendetta9"
      POSTGRES_DB: pessoas_tarefas
    ports:
      - "5432:5432"
    volumes:
      - pessoas-tarefas-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pessoas-tarefas-data: