# principal
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pessoas_tarefas
quarkus.datasource.username=postgres
quarkus.datasource.password=#Vendetta9
# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.port=8080
